add unittest for behaviour execution with subplans
rapyuta-robotics/alica pull request #166
Opened 2021-09-29 07:33 UTC by bjoernschroeder

2021-11-11 14:56 UTC, veerajsk requested changes

2021-11-11 14:56 UTC, veerajsk commented on alica_tests/autogenerated/include/ExecuteBehaviourPlan23172561495666303184.h
> +#pragma once
this plan does not have a corresponding pml file & seems to be unused. Can you remove all files relating to it?

2021-11-11 14:56 UTC, veerajsk commented on alica_tests/src/test/test_alica_scheduling.cpp
> +    std::this_thread::sleep_for(std::chrono::milliseconds(50));
this won't work as expected. There is nothing stopping the run method in TestBehaviour (ExecuteBehaviour state) from executing when the transitionToExecuteBehaviourInSubPlan is true. Instead you need to ascertain that run/terminate is called when the transition is true & then init/run is called for the next state. Have a look at the BehAAA & other scheduling tests to get an idea of how to do this.

2021-12-07 13:06 UTC, veerajsk approved these changes

2021-12-08 22:15 UTC, abhi1287 approved these changes

2021-12-09 06:21 UTC, merged