Remove AlicaEngine::this from Logger
rapyuta-robotics/alica pull request #293
Opened 2022-06-06 17:50 UTC by triccyx

Remove AlicaEngine::this from Logger and subclass

2022-07-25 13:22 UTC, veerajsk commented
@triccyx this PR includes changes from PR7 & if I change the base of the PR to PR7 it shows 292 file changes. This means the PR is still not correctly rebased on top of PR7. Can you please rebase correctly so that we can review multiple PRs at once?

2022-07-25 13:27 UTC, triccyx commented
Very strange ... I will rebase again

2022-07-25 21:24 UTC, triccyx commented
Ok rebase done

2022-07-26 13:21 UTC, christianhelm reviewed
What has changed in the binary files?

2022-07-26 13:21 UTC, christianhelm commented on alica_engine/include/engine/Logger.h
>  class AlicaEngine;
Remove AlicaEngine declaration

2022-07-26 13:21 UTC, christianhelm commented on alica_engine/include/engine/teammanager/TeamManager.h
>  struct AgentQuery;
Remove AlicaEngine declaration

2022-07-26 14:34 UTC, bjoernschroeder requested changes

2022-07-26 14:34 UTC, bjoernschroeder commented on alica_engine/include/engine/Logger.h
>  class AlicaEngine;
Forward declaration of engine can be removed

2022-07-26 14:34 UTC, bjoernschroeder commented on alica_engine/src/engine/Logger.cpp
> +        : _configChangeListener(configChangeListener)
We only use the configChangeListener in the constructor. We can use the passed instance to call subscribe and reload once and get rid of storing the configChangeListener locally.

2022-07-26 14:34 UTC, bjoernschroeder commented on alica_engine/src/engine/collections/RobotProperties.cpp
>  namespace alica
Engine include can be removed.

2022-07-26 14:34 UTC, bjoernschroeder commented on alica_engine/src/engine/collections/RobotEngineData.cpp
>  /**
Engine include can be removed

2022-07-26 14:34 UTC, bjoernschroeder commented on alica_engine/src/engine/teammanager/TeamManager.cpp
>  #include "engine/AlicaEngine.h"
You can remove the engine include and add the following includes instead:

#include "engine/IAlicaCommunication.h"
#include "engine/ConfigChangeListener.h"
#include "engine/PlanRepository.h"

2022-07-26 14:34 UTC, bjoernschroeder commented on alica_engine/src/engine/teammanager/TeamManager.cpp
> +        , _configChangeListener(configChangeListener)
the configChangeListener is only used in the constructor, we can use the passed instance directly and not store it locally.

2022-07-27 06:58 UTC, triccyx commented on alica_engine/include/engine/teammanager/TeamManager.h
>  struct AgentQuery;
ok

2022-07-27 06:58 UTC, triccyx commented on alica_engine/include/engine/Logger.h
>  class AlicaEngine;
ok

2022-07-27 07:00 UTC, triccyx commented on alica_engine/src/engine/Logger.cpp
> +        : _configChangeListener(configChangeListener)
ok

2022-07-27 07:00 UTC, triccyx commented on alica_engine/include/engine/Logger.h
>  class AlicaEngine;
ok

2022-07-27 07:10 UTC, triccyx commented on alica_engine/include/engine/Logger.h
>  class AlicaEngine;
I find out that I forget 2 functions, not class methods, that use AlicaEngine. 
```c++
std::string getLogFilename(AlicaEngine* ae, const std::string& file);
std::string getErrLogFilename(AlicaEngine* ae, const std::string& file);
```
I prefer to correct them in PR15 as leftover.
So I would leave AlicaEngine declaration in this PR

2022-07-27 15:47 UTC, triccyx commented on alica_engine/include/engine/Logger.h
>  class AlicaEngine;
@christianhelm 
commit in PR15
https://github.com/rapyuta-robotics/alica/commit/7cad0e7f5b0992ec55ef27a008ef65c063741d1c
and
https://github.com/rapyuta-robotics/alica/commit/b1bcf7b9fde8b289c6d172fccdcc3021240a7bc0

2022-07-28 13:16 UTC, christianhelm commented
The jar files need to be removed from this PR

2022-07-28 15:43 UTC, triccyx commented
> The jar files need to be removed from this PR

The only way I found to remove the files from commit was:
```
git reset --soft <the old commit>
git reset HEAD <file>
git commit --amend
push --force ....
```
Before I have tried simply with 
```
git checkout origin/rr_devel   -- <file name> 
```
but it won't work I think for some lfs issue.

It seems to me that this time the two files disappear from  PR and I hope I haven't 
destroy the branch

2022-08-01 06:31 UTC, christianhelm approved these changes

2022-08-01 07:28 UTC, veerajsk approved these changes

2022-08-01 08:59 UTC, bjoernschroeder approved these changes

2022-08-01 09:46 UTC, merged