Use blackboard to store WorldModels for libraries
rapyuta-robotics/alica pull request #360
Opened 2022-12-05 15:27 UTC by triccyx

Use AlicaEngine blackboard to store WorldModels for dynamically loaded libraries.

2022-12-06 06:02 UTC, veerajsk commented on alica_dynamic_loading/include/DynamicTransitionConditionCreator.h
> +    typedef bool(transitionConditionFunctionType)(const Blackboard*, const RunningPlan*, const Blackboard&*);
`const Blackboard*`

2022-12-06 06:02 UTC, veerajsk commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    T* getWorldModel(const std::string& libraryName)
- can't we use the existing `get` method? The key will be "worldModel" & type will be std::any for now.
- I don't think the library name should be necessary as a parameter. When namespacing is implemented (which can be done in a different PR) a `namespaced blackboard accessor` can internally deduce which namespace should be used.

2022-12-06 07:57 UTC, triccyx commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    T* getWorldModel(const std::string& libraryName)
@veerajsk 
> namespaced blackboard accessor an internally deduce which namespace should be used

This is not clear to me. How does it work?  Can you do an example? Do you mean to use typeid operator for search in the map?
For me namespacing in this case means a `const string libraryName` in the library, something like  "AlicaTurtlesim/worldmodel" and searching it in the map.

2022-12-13 08:16 UTC, triccyx commented
Ok, you can start reviewing. Some cleanup still needs and also I expect some discussions.

2022-12-20 13:46 UTC, veerajsk requested changes
@triccyx didn't we decide to have a single global blackboard which replaces the current world model & then implement namespacing on it later? This PR again makes multiple blackboards & world models.

2022-12-20 13:51 UTC, triccyx commented
Yes but as I have already done the work I haven't removed it. However, it is not a problem I can remove the methods.
Have you noticed this question:
https://github.com/rapyuta-robotics/alica/pull/360#discussion_r1040614339
 it is not clear to me how we want to implement the namespace

2022-12-20 14:02 UTC, veerajsk commented
> Yes but as I have already done the work I haven't removed it. However, it is not a problem I can remove the methods. Have you noticed this question: [#360 (comment)](https://github.com/rapyuta-robotics/alica/pull/360#discussion_r1040614339) it is not clear to me how we want to implement the namespace

we can think about namespacing later. For now just a global blackboard to replace the current world model is sufficient. The world model concept itself can be entirely removed. For turtlesim, its world model class can just be stored on the global blackboard in the init() of master plan.

2022-12-21 12:24 UTC, veerajsk requested changes

2022-12-21 12:24 UTC, veerajsk commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    std::unordered_map<std::string /*libraryname*/, std::any> _worldModels;
as I mentioned in previous comment, we can get rid of the world model concept entirely & replace with global blackboard. The only changes required are:
1. Replace all references to world model with global blackboard
2. Remove APIs to set/get world model in the alica context
There are no changes required to the blackboard APIs for now. The libraries can store whatever they want on the global blackboard using the existing blackboard APIs (including any world models, the engine is oblivious to it however). Then we can think of how to namespace the APIs as per library name in the global blackboard in different PR.
For turtlesim, the world model it uses will be stored on the global blackboard under the key "worldModel" in the init() of master plan.

2022-12-21 13:43 UTC, triccyx commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    std::unordered_map<std::string /*libraryname*/, std::any> _worldModels;
Ok, I remove also that part.

2023-01-02 08:30 UTC, veerajsk commented on alica_engine/include/engine/BasicPlan.h
> +    Blackboard& worldModels;
why is this variable named `worldModels`? Can't we just call it global blackboard?

2023-01-02 08:31 UTC, veerajsk commented on alica_engine/include/engine/PlanBase.h
> +    void start(const Plan* masterPlan, const Blackboard& globalBlackboard);
Taking the global blackboard as a parameter here is strange. Isn't this just the `globalBlackboard` memeber variable?

2023-01-02 10:15 UTC, veerajsk commented on supplementary/alica_ros1/alica_ros_turtlesim/Expr/src/LegacyTransitionConditionCreator.cpp
> +LegacyTransitionConditionCreator::LegacyTransitionConditionCreator() {}
@bjoernschroeder didn't you re-generate code for alica_ros_turtlesim in the legacy transition conditions PR?

2023-01-02 10:15 UTC, veerajsk commented on supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/include/world_model.hpp
> +#pragma GCC diagnostic push
I don't think there is any need to suppress this warning. Rather we should remove the use of the deprecated function eventually & the warning will help as a reminder. 
Should be able to easily remove this function once https://github.com/rapyuta-robotics/alica/pull/338 is merged

2023-01-02 10:15 UTC, veerajsk commented on supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/Go2RandomPosition.cpp
> +    turtlesim::ALICATurtleWorldModel* wm = LockedBlackboardRW(getGlobalBlackboard()).get<std::shared_ptr<turtlesim::ALICATurtleWorldModel>>("worldmodel").get();
The shared_ptr will be destroyed at the end of this statement. So essentially there is no utility in storing a shared_ptr. So, either make wm a shared_ptr or directly store the raw pointer. imo, I prefer the former

2023-01-02 10:15 UTC, veerajsk commented on supplementary/alica_ros1/alica_ros_turtlesim/Expr/include/alica/conditions/conditions.h
> +bool conditionMove2Init748720375848597116(const Blackboard* input, const RunningPlan* rp, const Blackboard* wm);
rename wm -> gb or globalBB?

2023-01-02 10:15 UTC, veerajsk commented on alica_engine/include/engine/AlicaContext.h
> +    void startEngine();
can't the blackboard be stored in the AlicaContext instead & the world model set by some init plan in the library? Then this function can be removed

2023-01-02 17:42 UTC, triccyx commented on alica_engine/include/engine/AlicaContext.h
> +    void startEngine();
Yes, done.

2023-01-02 17:58 UTC, triccyx commented on supplementary/alica_ros1/alica_ros_turtlesim/Expr/include/alica/conditions/conditions.h
> +bool conditionMove2Init748720375848597116(const Blackboard* input, const RunningPlan* rp, const Blackboard* wm);
Ok, I need to change also the template sfor code gen.

2023-01-02 18:46 UTC, triccyx commented on alica_engine/include/engine/PlanBase.h
> +    void start(const Plan* masterPlan, const Blackboard& globalBlackboard);
Yes, leftover.

2023-01-04 17:32 UTC, triccyx commented on supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/include/world_model.hpp
> +#pragma GCC diagnostic push
ok!

2023-01-04 18:01 UTC, triccyx commented on alica_engine/include/engine/BasicPlan.h
> +    Blackboard& worldModels;
leftover

2023-01-04 18:14 UTC, triccyx commented on supplementary/alica_ros1/alica_ros_turtlesim/alica_turtlesim_library/src/Go2RandomPosition.cpp
> +    turtlesim::ALICATurtleWorldModel* wm = LockedBlackboardRW(getGlobalBlackboard()).get<std::shared_ptr<turtlesim::ALICATurtleWorldModel>>("worldmodel").get();
Yes an error.

2023-01-11 08:56 UTC, veerajsk commented on alica_engine/include/engine/AlicaContext.h
> +     * Get blackboard list being used by this alica instance.
blackboard list?

```suggestion
     * Get the global blackboard associated with this instance of the alica context
```

2023-01-11 08:56 UTC, veerajsk commented on alica_engine/include/engine/AlicaContext.h
> +     * @return A reference to blackboard being used by context.
```suggestion
     * @return A reference to the global blackboard
```

2023-01-11 08:56 UTC, veerajsk commented on alica_engine/include/engine/AlicaEngine.h
> +    Blackboard& _globalBlackboard;
no need to store the blackboard reference again. The engine can access it via `_ctx.getBlackboard()` or `_ctx.editBlackboard()`

2023-01-11 08:56 UTC, veerajsk commented on alica_engine/include/engine/RuleBook.h
> +    const Blackboard* _globalBlackboard;
nit: its a bit weird that references to the blackboard are passed in the constructors, but pointers are stored/passed in places where it is actually used. We can stick to any one. Since we were passing a pointer to the global world model I think we can just retain that

2023-01-11 08:56 UTC, veerajsk commented on alica_engine/include/engine/RunnableObject.h
> +    Blackboard& getGlobalBlackboard() { return _globalBlackboard; };
I think its better to return a raw pointer here since `getBlackboard()` also returns a pointer type & also because the blackboard is passed as a pointer to transitions. As I said earlier best to stick to any one syntax so that user code that uses it is consistent

2023-01-11 08:56 UTC, veerajsk commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    mutable std::shared_lock<std::shared_mutex> _lk;
why?

2023-01-11 08:56 UTC, veerajsk commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    mutable std::unique_lock<std::shared_mutex> _lk;
why?

2023-01-11 08:56 UTC, veerajsk commented on supplementary/alica_ros1/alica_ros_turtlesim/src/base.cpp
> -        ac->setWorldModel<turtlesim::ALICATurtleWorldModel>(nh, priv_nh);
why does nh & priv_nh have to be passed in start? Can you not set the world model on the global blackboard here itself?

2023-01-11 09:46 UTC, triccyx commented on alica_engine/include/engine/AlicaEngine.h
> +    Blackboard& _globalBlackboard;
Yes, sure

2023-01-11 09:51 UTC, triccyx commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    mutable std::shared_lock<std::shared_mutex> _lk;
Uhm I don't remember. Perhaps some problems with `const` in the old version. But removed

2023-01-11 09:52 UTC, triccyx commented on alica_engine/include/engine/blackboard/Blackboard.h
> +    mutable std::unique_lock<std::shared_mutex> _lk;
As above

2023-01-11 10:15 UTC, triccyx commented on supplementary/alica_ros1/alica_ros_turtlesim/src/base.cpp
> -        ac->setWorldModel<turtlesim::ALICATurtleWorldModel>(nh, priv_nh);
Leftover. This was due to the fact that globalBlackoard was in AlicaEngine. No more necessary as now it is in AlicaContext

2023-01-11 10:58 UTC, triccyx commented on alica_engine/include/engine/RunnableObject.h
> +    Blackboard& getGlobalBlackboard() { return _globalBlackboard; };
ok

2023-01-11 14:02 UTC, triccyx commented on alica_engine/include/engine/RuleBook.h
> +    const Blackboard* _globalBlackboard;
ok. For coherency I have also changed in PlanSelector.

2023-01-13 06:29 UTC, veerajsk approved these changes

2023-01-16 08:50 UTC, ntfshard reviewed
I really like to moving from raw pointers to references/smart pointers, but I suppose there are some places where it could be also applied. Maybe not in this PR

2023-01-16 08:50 UTC, ntfshard commented on alica_engine/include/engine/Types.h
> +using TransitionConditionCallback = std::function<bool(const Blackboard*, const RunningPlan*, const Blackboard*)>;
can't use ref here? from one side inconsistent, but for c++ imho references is more preferable

2023-01-16 08:50 UTC, ntfshard commented on alica_engine/include/engine/Types.h
> +using TransitionConditionCallback = std::function<bool(const Blackboard*, const RunningPlan*, const Blackboard*)>;
same in other places

2023-01-16 08:50 UTC, ntfshard commented on alica_engine/src/engine/AlicaContext.cpp
> +
empty line?

2023-01-16 08:50 UTC, ntfshard commented on cmake_flags/cflags.cmake
> +set(CPP_ERROR "-Werror -Wno-error=deprecated-declarations")
we need it?

2023-01-16 08:50 UTC, ntfshard commented on supplementary/alica_ros1/alica_tests/include/test_alica.h
> +        manageWorldModel(ac);
curious, why we moved it here

2023-01-17 07:45 UTC, triccyx commented on cmake_flags/cflags.cmake
> +set(CPP_ERROR "-Werror -Wno-error=deprecated-declarations")
Yes, in this way, we will remember to remove deprecated in favor of the new API from another PR

2023-01-17 17:14 UTC, triccyx commented on alica_engine/include/engine/Types.h
> +using TransitionConditionCallback = std::function<bool(const Blackboard*, const RunningPlan*, const Blackboard*)>;
Yes, you are right. But AlicaContext::_globalBlackBoard  is passed down as a reference as far as possible in the constructors below. When it is not possible (for example RuleBook::init) it is passed as a pointer. In RuleBook we can not leave the _globalBlackboard var as a hanging reference -> so pointer.

2023-01-17 22:03 UTC, triccyx commented on alica_engine/src/engine/AlicaContext.cpp
> +
removed

2023-01-17 22:04 UTC, triccyx commented on supplementary/alica_ros1/alica_tests/include/test_alica.h
> +        manageWorldModel(ac);
Yes we need to do some `init` before setWorldModel

2023-01-18 04:50 UTC, Dale-Koenig approved these changes
Okay but please wait to merge until we update LBC to latest devel

2023-01-18 04:50 UTC, Dale-Koenig commented on alica_engine/include/engine/IAlicaTrace.h
> +    virtual void setLog(const std::pair<std::string_view, TraceValue>& fields) { log({{fields.first, fields.second}}); }
Why does this need to be virtual?

2023-01-18 04:50 UTC, Dale-Koenig commented on alica_engine/include/engine/PlanBase.h
> +class Blackboard;
nit:  These are supposed to be in alphabetical order everywhere

2023-01-18 04:50 UTC, Dale-Koenig commented on supplementary/alica_ros1/alica_ros_turtlesim/Expr/src/GoTo.cpp
> +    std::shared_ptr<turtlesim::ALICATurtleWorldModel> wm =
nit:  This can be a read lock to just get blackboard to access world model

2023-01-18 07:13 UTC, triccyx commented on alica_engine/include/engine/PlanBase.h
> +class Blackboard;
I'm quite sure that clang `SortInclude` does not sort forward declarations and there is no other sort directive for this that I know.
So the work should be done by hand.

2023-01-18 07:19 UTC, triccyx commented on alica_engine/include/engine/IAlicaTrace.h
> +    virtual void setLog(const std::pair<std::string_view, TraceValue>& fields) { log({{fields.first, fields.second}}); }
leftover from a prev implementation. Removed

2023-01-18 07:34 UTC, triccyx commented on supplementary/alica_ros1/alica_ros_turtlesim/Expr/src/GoTo.cpp
> +    std::shared_ptr<turtlesim::ALICATurtleWorldModel> wm =
ok

2023-01-19 22:09 UTC, merged