Add tests to ROS1 turtlesim
rapyuta-robotics/alica pull request #376
Opened 2022-12-26 05:52 UTC by dhananjay-patki

Added a test to the ros1 turtlesim

2023-01-01 09:55 UTC, triccyx reviewed
Only a small note

2023-01-01 09:55 UTC, triccyx commented on supplementary/alica_ros1/alica_ros_turtlesim/test/test_main.cpp
> +    double getX() { return x; }
These methods can be const

2023-01-05 06:54 UTC, bjoernschroeder approved these changes

2023-01-10 09:11 UTC, Dale-Koenig commented on supplementary/alica_ros1/alica_ros_turtlesim/CMakeLists.txt
> +include(CTest)
Since this is ROS package can use the more standard catkin cmake macros

2023-01-10 09:11 UTC, Dale-Koenig commented on supplementary/alica_ros1/alica_ros_turtlesim/test/test_main.cpp
> +    std::this_thread::sleep_for(1s);
can RUN_UNTIL

2023-01-10 09:11 UTC, Dale-Koenig commented on supplementary/alica_ros1/alica_ros_turtlesim/test/test_main.cpp
> +    EXPECT_EQ(init_pub.getNumSubscribers(), 4U);
ASSERT_EQ

2023-01-10 09:11 UTC, Dale-Koenig commented on supplementary/alica_ros1/alica_ros_turtlesim/test/test_main.cpp
> +        init_pub.publish(msg);
Once should be enough?

2023-02-20 05:27 UTC, veerajsk requested changes
needs to change as per new turtlesim implementation

2023-03-02 03:10 UTC, closed without merging